/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.EmployerRole;

/**
 *
 * @author rohan
 */
public class ManageFacultyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudentJPanel
     */
    public ManageFacultyJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelManageFaculty = new javax.swing.JLabel();
        labelFacultyName = new javax.swing.JLabel();
        labelFacultyUsername = new javax.swing.JLabel();
        labelFacultyPassword = new javax.swing.JLabel();
        textFacultyName = new javax.swing.JTextField();
        textFacultyUsername = new javax.swing.JTextField();
        PasswordFieldFaculty = new javax.swing.JPasswordField();
        buttonCreateFaculty = new javax.swing.JButton();

        labelManageFaculty.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelManageFaculty.setText("Manage Faculty");

        labelFacultyName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFacultyName.setText("Faculty Name:");

        labelFacultyUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFacultyUsername.setText("Username:");

        labelFacultyPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFacultyPassword.setText("Password:");

        buttonCreateFaculty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCreateFaculty.setText("Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(602, 602, 602)
                        .addComponent(labelManageFaculty))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFacultyUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFacultyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordFieldFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFacultyUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(642, 642, 642)
                        .addComponent(buttonCreateFaculty)))
                .addContainerGap(549, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelManageFaculty)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFacultyUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFacultyUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelFacultyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PasswordFieldFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(buttonCreateFaculty)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordFieldFaculty;
    private javax.swing.JButton buttonCreateFaculty;
    private javax.swing.JLabel labelFacultyName;
    private javax.swing.JLabel labelFacultyPassword;
    private javax.swing.JLabel labelFacultyUsername;
    private javax.swing.JLabel labelManageFaculty;
    private javax.swing.JTextField textFacultyName;
    private javax.swing.JTextField textFacultyUsername;
    // End of variables declaration//GEN-END:variables
}
