/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author rohan
 */
public class EmployerDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployerDashboardJPanel
     */
    public EmployerDashboardJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEmployerDashboard = new javax.swing.JLabel();
        buttonEmployerManageStudents = new javax.swing.JButton();
        buttonEmployerManageFaculty = new javax.swing.JButton();
        buttonEmployerManageTranscript = new javax.swing.JButton();
        buttonEmployerLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        labelEmployerDashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelEmployerDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmployerDashboard.setText("Hello Employer");
        labelEmployerDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        buttonEmployerManageStudents.setBackground(new java.awt.Color(153, 153, 153));
        buttonEmployerManageStudents.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonEmployerManageStudents.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmployerManageStudents.setText("Manage Students");

        buttonEmployerManageFaculty.setBackground(new java.awt.Color(153, 153, 153));
        buttonEmployerManageFaculty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonEmployerManageFaculty.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmployerManageFaculty.setText("Manage Faculty");

        buttonEmployerManageTranscript.setBackground(new java.awt.Color(153, 153, 153));
        buttonEmployerManageTranscript.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonEmployerManageTranscript.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmployerManageTranscript.setText("Manage Transcript");

        buttonEmployerLogout.setBackground(new java.awt.Color(153, 153, 153));
        buttonEmployerLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonEmployerLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmployerLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(buttonEmployerManageStudents)
                        .addGap(218, 218, 218)
                        .addComponent(buttonEmployerManageFaculty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEmployerLogout)
                        .addGap(110, 110, 110)))
                .addComponent(buttonEmployerManageTranscript)
                .addGap(453, 453, 453))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelEmployerDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelEmployerDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonEmployerManageTranscript)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEmployerManageStudents)
                    .addComponent(buttonEmployerManageFaculty))
                .addGap(127, 127, 127)
                .addComponent(buttonEmployerLogout)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEmployerLogout;
    private javax.swing.JButton buttonEmployerManageFaculty;
    private javax.swing.JButton buttonEmployerManageStudents;
    private javax.swing.JButton buttonEmployerManageTranscript;
    private javax.swing.JLabel labelEmployerDashboard;
    // End of variables declaration//GEN-END:variables
}
