/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author rohan
 */
public class ProfessorLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentLoginJPanel
     */
    public ProfessorLoginJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProfessorLogin = new javax.swing.JLabel();
        labelProfessorLoginUsername = new javax.swing.JLabel();
        labelProfessorLoginPassword = new javax.swing.JLabel();
        textProfessorLoginUsername = new javax.swing.JTextField();
        textProfessorLoginPassword = new javax.swing.JTextField();
        buttonProfessorLoginSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelProfessorLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelProfessorLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProfessorLogin.setText("Professor Login");
        labelProfessorLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        labelProfessorLoginUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelProfessorLoginUsername.setText("Username:");
        labelProfessorLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelProfessorLoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelProfessorLoginPassword.setText("Password:");
        labelProfessorLoginPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        textProfessorLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        textProfessorLoginPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        buttonProfessorLoginSubmit.setBackground(new java.awt.Color(153, 153, 153));
        buttonProfessorLoginSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buttonProfessorLoginSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonProfessorLoginSubmit.setText("Login");
        buttonProfessorLoginSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelProfessorLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelProfessorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textProfessorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addComponent(buttonProfessorLoginSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelProfessorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelProfessorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProfessorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(buttonProfessorLoginSubmit)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProfessorLoginSubmit;
    private javax.swing.JLabel labelProfessorLogin;
    private javax.swing.JLabel labelProfessorLoginPassword;
    private javax.swing.JLabel labelProfessorLoginUsername;
    private javax.swing.JTextField textProfessorLoginPassword;
    private javax.swing.JTextField textProfessorLoginUsername;
    // End of variables declaration//GEN-END:variables
}
